name: Release on Tag
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@v3

      - name: Configure
        run: |
          cmake -B build -DPRINT_VERSION=${{ github.ref_name#v }}

      - name: Build
        run: cmake --build build --config Release --parallel $(nproc)

      - name: Package (CPack)
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          cpack --config build/CPackConfig.cmake -G ${% if runner.os == 'Windows' %}WIX${% elif runner.os == 'macOS' %}DragNDrop${% else %}DEB;RPM${% endif %} -B artifacts/${{ matrix.os }}

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-packages
          path: artifacts/${{ matrix.os }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ github.ref_name }}
          artifacts: "all-artifacts/**/*"
          token: ${{ secrets.GITHUB_TOKEN }}
