name: CMake

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure Solver
      run: cmake -B build
    - name: Build Solver
      run: cmake --build build
    - name: Build packages
      run: |
        cmake --build build --target package
        cmake --build build --target package_source
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-packages
        path: |
          build/*.deb
          build/*.rpm
          build/*.tar.gz
          build/*.zip

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure Solver
      run: cmake -B build -G "Visual Studio 17 2022"
    - name: Build Solver
      run: cmake --build build --config Release
    - name: Build package
      run: cmake --build build --target package --config Release
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-packages
        path: build/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure Solver
      run: cmake -B build
    - name: Build Solver
      run: cmake --build build
    - name: Build package
      run: cmake --build build --target package
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-packages
        path: build/*.dmg

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Create Release
      uses: ncipollo/release-action@v1.16.0
      with:
        artifacts: "artifacts/**/*"
        token: ${{ secrets.GITHUB_TOKEN }}
