name: CMake

on:
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build
    - name: Create Packages
      run: |
        cmake --build build --target package
        cpack -B build/packages -G DEB
        cpack -B build/packages -G RPM

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build
    - name: Install WiX
      run: choco install wixtoolset
    - name: Create MSI
      run: cpack -B build/packages -G WIX

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build
    - name: Create DMG
      run: cpack -B build/packages -G DragNDrop

  create-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: Create Release
      uses: ncipollo/release-action@v1.16.0
      with:
        artifacts: "artifacts/**/*"
        token: ${{ secrets.GITHUB_TOKEN }}
