name: CMake Package and Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Необходимо для создания релиза

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Build Package
      run: cmake --build build --target package

    - name: Build Source Package
      run: cmake --build build --target package_source

    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "build/*.deb,build/*.rpm,build/*.tar.gz,build/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
